#!/bin/sh
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "Installing terraform binary"
mkdir -p /var/tmp/terraform_install
cd /var/tmp/terraform_install
curl https://releases.hashicorp.com/terraform/1.1.4/terraform_1.1.4_linux_amd64.zip --output terraform_1.1.4_linux_amd64.zip
unzip terraform_1.1.4_linux_amd64.zip
mv ./terraform /usr/local/bin

exit 0
