#!/bin/sh
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the check script"

set -e

cd /root/reset-default-password

if ! terraform show | grep citrixadc_password_resetter ; then
  fail-message "Terraform state does not contain a password resetter resource"
  exit 1
fi

exit 0
