#!/bin/sh
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

if ! which terraform ; then
  fail-message "Terraform binary not found in PATH"
  exit 1
fi
exit 0
