#!/bin/sh
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the check script"

set -e

cd /root/apply-cs-configuration

if terraform show | grep citrixadc_csvserver ; then
  fail-message "Terraform state does still contains the lb vserver resource"
  exit 1
fi


exit 0
