#!/bin/sh
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the solve script"
set -e
cd /root/apply-cs-configuration
terraform destroy -var-file example.tfvars -auto-approve

exit 0
