#!/bin/bash

mkdir -p /root/citrixadc-ansible-track/

cd /root/citrixadc-ansible-track/

ADC_INSTANCE_NSIP=`gcloud compute instances describe --zone europe-west1-b adc-demo --format="value(networkInterfaces[0].accessConfigs[0].natIP)"`
ADC_INSTANCE_VIP=`gcloud compute instances describe --zone europe-west1-b adc-demo --format="value(networkInterfaces[1].networkIP)"`
ADC_INSTANCE_SNIP=`gcloud compute instances describe --zone europe-west1-b adc-demo --format="value(networkInterfaces[2].networkIP)"`
ADC_INSTANCE_ID=`gcloud compute instances describe --zone europe-west1-b adc-demo --format="value(id)"`
BACKEND_SERVER1_IP=`gcloud compute instances describe --zone europe-west1-b backend-server-1 --format="value(networkInterfaces[0].networkIP)"`
BACKEND_SERVER2_IP=`gcloud compute instances describe --zone europe-west1-b backend-server-2 --format="value(networkInterfaces[0].networkIP)"`

cat <<EOF > inventory.txt
[citrix_adc]
myadc snip=${ADC_INSTANCE_SNIP} vip_ip=${ADC_INSTANCE_VIP} nsip=${ADC_INSTANCE_NSIP} nitro_user=nsroot default_password=${ADC_INSTANCE_ID}  new_password=verystrongpassword validate_certs=no server1_ip=${BACKEND_SERVER1_IP} server2_ip=${BACKEND_SERVER2_IP}

EOF

cat <<EOF > citrixadc-first-time-password-reset.yaml
---

- hosts: citrix_adc

  gather_facts: False
  collections:
    - citrix.adc

  tasks:

    - name: Password reset
      delegate_to: localhost
      citrix_adc_password_reset:
        nsip: "{{ nsip }}"
        username: "{{ nitro_user }}"
        nitro_protocol: https
        validate_certs: no
        password: "{{ default_password }}"
        new_password: "{{ new_password }}"
EOF

cat <<EOF > citrixadc-setuplb.yaml
---

- hosts: citrix_adc

  vars:
    max_clients: 5

  remote_user: root
  gather_facts: False
  collections:
    - citrix.adc

  tasks:
    - name: Add SNIP
      delegate_to: localhost
      citrix_adc_nsip:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ new_password }}"
        validate_certs: no

        state: present

        ipaddress: "{{ snip }}"
        netmask: 255.255.255.0
        type: SNIP
        snmp: disabled

    - name: service-http-1
      delegate_to: localhost
      citrix_adc_service:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ new_password }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        name: service-http-1
        servicetype: HTTP
        ipaddress: "{{ server1_ip }}"
        port: 80

    - name: service-http-2
      delegate_to: localhost
      citrix_adc_service:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ new_password }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        name: service-http-2
        servicetype: HTTP
        ipaddress: "{{ server2_ip }}"
        port: 80

    - name: lb vserver 1
      delegate_to: localhost
      citrix_adc_lb_vserver:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ new_password }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        name: lb-vserver-1
        servicetype: HTTP
        timeout: 12
        ipv46: "{{ vip_ip }}"
        port: 80
        lbmethod: ROUNDROBIN
        servicebindings:
            - servicename: service-http-1
              weight: 50
            - servicename: service-http-2
              weight: 50
        disabled: no

EOF

ls


