#!/bin/sh
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#


mkdir -p /var/tmp/first_time_password_reset

cd /var/tmp/first_time_password_reset

ADC_INSTANCE_ID=`gcloud compute instances describe --zone europe-west1-b adc-demo --format="value(id)"`
ADC_INSTANCE_NSIP=`gcloud compute instances describe --zone europe-west1-b adc-demo --format="value(networkInterfaces[0].accessConfigs[0].natIP)"`

# provider.tf
cat <<EOF >provider.tf

terraform {
  required_providers {
    citrixadc = {
      source = "citrix/citrixadc"
    }
  }
}

provider "citrixadc" {
  endpoint = "http://${ADC_INSTANCE_NSIP}"
  username = "nsroot"
  password = "notnsroot"
}

EOF

# resources.tf
cat <<EOF >resources.tf

resource "citrixadc_password_resetter" "tf_resetter" {
    username = "nsroot"
    password = "${ADC_INSTANCE_ID}"
    new_password = "notnsroot"
}

EOF

sleep 10

terraform init

sleep 5

terraform apply -auto-approve

exit 0
