#!/bin/bash
# check
echo "Checking the solution of the challenge"

ansible --version

if [ $? -eq 0 ]; then
    exit 0
else
    echo "FAIL: Ansible NOT installed! Please all the pre-requisities"
    echo 1
fi